// AUTO-GENERATED by scripts/build-documents.mjs — do not edit by hand.
// Drop files into public/documents/ and re-run `npm run documents`.
import type { DocItem } from '../types.js';

export const DOCUMENTS: DocItem[] = [
	{
		"id": "1. INTERNATIONAL FLIGHTS.pdf",
		"name": "1. INTERNATIONAL FLIGHTS",
		"url": "/documents/1.%20INTERNATIONAL%20FLIGHTS.pdf",
		"filename": "1. INTERNATIONAL FLIGHTS.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 315109
	},
	{
		"id": "2. ACCOMMODATION.pdf",
		"name": "2. ACCOMMODATION",
		"url": "/documents/2.%20ACCOMMODATION.pdf",
		"filename": "2. ACCOMMODATION.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 249286
	},
	{
		"id": "3. 25 JUL - SEO - JEJ Flight.pdf",
		"name": "3. 25 JUL SEO JEJ Flight",
		"url": "/documents/3.%2025%20JUL%20-%20SEO%20-%20JEJ%20Flight.pdf",
		"filename": "3. 25 JUL - SEO - JEJ Flight.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 71594
	},
	{
		"id": "4. 28 JUL - JEJ - BUS Flight.pdf",
		"name": "4. 28 JUL JEJ BUS Flight",
		"url": "/documents/4.%2028%20JUL%20-%20JEJ%20-%20BUS%20Flight.pdf",
		"filename": "4. 28 JUL - JEJ - BUS Flight.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 56080
	},
	{
		"id": "5. 01 AUG - BUS - SEO Train.pdf",
		"name": "5. 01 AUG BUS SEO Train",
		"url": "/documents/5.%2001%20AUG%20-%20BUS%20-%20SEO%20Train.pdf",
		"filename": "5. 01 AUG - BUS - SEO Train.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 118555
	},
	{
		"id": "chopstick_tevlen.pdf",
		"name": "chopstick tevlen",
		"url": "/documents/chopstick_tevlen.pdf",
		"filename": "chopstick_tevlen.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 2111444
	},
	{
		"id": "city_tour_tevlen.pdf",
		"name": "city tour tevlen",
		"url": "/documents/city_tour_tevlen.pdf",
		"filename": "city_tour_tevlen.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 628446
	},
	{
		"id": "everland_tevlen.pdf",
		"name": "everland tevlen",
		"url": "/documents/everland_tevlen.pdf",
		"filename": "everland_tevlen.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 89388
	},
	{
		"id": "NOTES.pdf",
		"name": "NOTES",
		"url": "/documents/NOTES.pdf",
		"filename": "NOTES.pdf",
		"ext": ".pdf",
		"kind": "pdf",
		"size": 3093776
	}
];
